apiVersion: apps/v1
kind: Deployment
metadata:
  name: joomla
spec:
  replicas: 2
  selector:
    matchLabels:
      app: joomla
  template:
    metadata:
      labels:
        app: joomla
    spec:
      containers:
        - name: joomla-csm
          image: webapp:1
          # for local development against minikube registry
          #imagePullPolicy: Never
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: joomla-service
  labels:
    app: joomla-service
spec:
  type: NodePort
  ports:
    # the port that this service should serve on
    - port: 80
      targetPort: 80
  # label keys and values that must match in order to receive traffic for this service
  selector:
    app: joomla